require('config.globals')
require('config.options')
require('config.markdown-preview')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('config.nightfox')
-- require('config.catppuccin')
-- require('config.treesitter')
